from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    IntegerType,
    LongType,
    DateType,
    FloatType,
)

listings_schema = StructType(
    [
        StructField("id", LongType()),
        StructField("listing_url", StringType()),
        StructField("scrape_id", LongType()),
        StructField("last_scraped", DateType()),
        StructField("source", StringType()),
        StructField("name", StringType()),
        StructField("description", StringType()),
        StructField("neighborhood_overview", StringType()),
        StructField("picture_url", StringType()),
        StructField("host_id", LongType()),
        StructField("host_url", StringType()),
        StructField("host_name", StringType()),
        StructField("host_since", DateType()),
        StructField("host_location", StringType()),
        StructField("host_about", StringType()),
        StructField("host_response_time", StringType()),
        StructField("host_response_rate", StringType()),
        StructField("host_acceptance_rate", StringType()),
        StructField("host_is_superhost", StringType()),
        StructField("host_thumbnail_url", StringType()),
        StructField("host_picture_url", StringType()),
        StructField("host_neighbourhood", StringType()),
        StructField("host_listings_count", IntegerType()),
        StructField("host_total_listings_count", IntegerType()),
        StructField("host_verifications", StringType()),
        StructField("host_has_profile_pic", StringType()),
        StructField("host_identity_verified", StringType()),
        StructField("neighbourhood", StringType()),
        StructField("neighbourhood_cleansed", StringType()),
        StructField("neighbourhood_group_cleansed", StringType()),
        StructField("latitude", FloatType()),
        StructField("longitude", FloatType()),
        StructField("property_type", StringType()),
        StructField("room_type", StringType()),
        StructField("accommodates", IntegerType()),
        StructField("bathrooms", IntegerType()),
        StructField("bathrooms_text", StringType()),
        StructField("bedrooms", IntegerType()),
        StructField("beds", IntegerType()),
        StructField("amenities", StringType()),
        StructField("price", StringType()),
        StructField("minimum_nights", IntegerType()),
        StructField("maximum_nights", IntegerType()),
        StructField("minimum_minimum_nights", IntegerType()),
        StructField("maximum_minimum_nights", IntegerType()),
        StructField("minimum_maximum_nights", IntegerType()),
        StructField("maximum_maximum_nights", IntegerType()),
        StructField("minimum_nights_avg_ntm", IntegerType()),
        StructField("maximum_nights_avg_ntm", IntegerType()),
        StructField("calendar_updated", StringType()),
        StructField("has_availability", StringType()),
        StructField("availability_30", IntegerType()),
        StructField("availability_60", IntegerType()),
        StructField("availability_90", IntegerType()),
        StructField("availability_365", IntegerType()),
        StructField("calendar_last_scraped", DateType()),
        StructField("number_of_reviews", IntegerType()),
        StructField("number_of_reviews_ltm", IntegerType()),
        StructField("number_of_reviews_l30d", IntegerType()),
        StructField("first_review", DateType()),
        StructField("last_review", DateType()),
        StructField("review_scores_rating", FloatType()),
        StructField("review_scores_accuracy", FloatType()),
        StructField("review_scores_cleanliness", FloatType()),
        StructField("review_scores_checkin", FloatType()),
        StructField("review_scores_communication", FloatType()),
        StructField("review_scores_location", FloatType()),
        StructField("review_scores_value", FloatType()),
        StructField("license", StringType()),
        StructField("instant_bookable", StringType()),
        StructField("calculated_host_listings_count", IntegerType()),
        StructField("calculated_host_listings_count_entire_homes", IntegerType()),
        StructField("calculated_host_listings_count_private_rooms", IntegerType()),
        StructField("calculated_host_listings_count_shared_rooms", IntegerType()),
        StructField("reviews_per_month", FloatType()),
    ]
)

calendar_schema = StructType(
    [
        StructField("listing_id", LongType()),
        StructField("date", DateType()),
        StructField("available", StringType()),
        StructField("price", StringType()),
        StructField("adjusted_price", StringType()),
        StructField("minimum_nights", IntegerType()),
        StructField("maximum_nights", IntegerType()),
    ]
)

reviews_schema = StructType(
    [
        StructField("listing_id", LongType()),
        StructField("id", LongType()),
        StructField("date", DateType()),
        StructField("reviewer_id", LongType()),
        StructField("reviewer_name", StringType()),
        StructField("comments", StringType()),
    ]
)
